#!/usr/bin/env node

const http = require('http');
const colors = require('colors');
const querystring = require('querystring');
const fs = require('fs');
const url = 'http://fanyi.youdao.com/openapi.do?keyfrom=bladetrans&key=902909552&type=data&doctype=json&version=1.1&q=';

let params = process.argv.slice(2).join(' ')
params = querystring.escape(params)

new Promise(function (resolve, reject) {
  let data = ""
  http.get(url + params, function (res) {
    res.on('data', function (result) {
      data += result;
    })
    res.on('end', function () {
      resolve(data)
    })
  }).on('error', function (e) {
    reject(e)
  })
})
.then(function (data) {
  data = JSON.parse(data)

  process.stdout.write(`
    - ${data.translation[0].green || ""} \n`)


  if (!data.web || (Array.isArray(data.web) && data.web.length == 0)) return
  let print = ``
  data.web.forEach( (item, index) => {
    print += `
    ${++index}. ${item.key ? item.key.yellow : ''} \n
      ${item.value ? item.value.join(',') : ''} \n\n`
  })
  process.stdout.write(print)
  
})
.catch(console.log)